apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
      - image: gajjarashish/database:V0.01
        imagePullPolicy: ""
        name: database
        resources: {}
        volumeMounts:
         - name: database
           mountPath: /data/db
      restartPolicy: Always
      volumes:
       - name: database
         persistentVolumeClaim:
           claimName: database-pvc
